server.servlet.context-path=/lms
spring.datasource.url=jdbc:mysql://localhost:3306/lmsapp
spring.datasource.username=root
spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=create
spring.web.error.include-filter=false
